import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, ClipboardCheck, FileText, MessageSquare, PenTool, Receipt, Ruler } from "lucide-react";
import { ProjectSelector } from "@/components/ProjectSelector";
import { BuildCostCalculator } from "@/components/BuildCostCalculator";

const benefits=[["Fixed fees, no surprises","Every stage priced up front.",Receipt],["Planning expertise","Applications framed around policy and constraints.",ClipboardCheck],["Direct architect access","You work directly with David.",MessageSquare],["Drawings and submissions","Survey, planning and technical information.",FileText],["Technical coordination","Building Regulations and engineer coordination.",Building2],["Clear process","A staged route from feasibility to construction.",PenTool]];

export default function Page(){
 return <>
  <section className="hero"><div className="shell herogrid"><div><div className="eyebrow">Residential architecture · ARB · RIBA</div><h1>Know what your project needs <em>before you commit a penny.</em></h1><p>Hepburn Architects helps homeowners understand feasibility, planning risk and likely cost — then delivers the drawings and submissions needed to move forward.</p><div className="actions"><Link href="/estimate" className="btn primary">Get my project estimate <ArrowRight size={17}/></Link><a className="btn secondary" href="mailto:hello@hepburnarchitects.net">Book a free consultation</a></div></div>
  <div className="heroimg"><Image src="https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=90" alt="Contemporary residential extension" width={1000} height={1200} priority/></div></div></section>
  <section className="section sand"><div className="shell"><ProjectSelector/></div></section>
  <section className="section"><div className="shell twocol"><div><div className="eyebrow">Why Hepburn Architects</div><h2>Architect-led. Fixed-fee. Straight-talking.</h2><p>A residential architectural service designed around clarity, direct communication and informed planning advice.</p></div><div className="benefits">{benefits.map(([t,b,I]:any)=><article key={t}><I/><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
  <section className="section sand"><div className="shell twocol"><div><div className="eyebrow">Build Cost Calculator</div><h2>How much could the build itself cost?</h2><p>A quick indicative range for early conversations. It is not a quotation or professional cost plan.</p></div><BuildCostCalculator/></div></section>
  <section className="section dark"><div className="shell founder"><Image src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=900&q=85" alt="Founder portrait placeholder" width={700} height={850}/><div><div className="eyebrow">Founder-led practice</div><h2>You’ll speak to David, not a call centre.</h2><p>Every project starts with a direct conversation about feasibility, planning, costs and the right next step.</p><ul><li><CheckCircle2/> ARB-registered architect</li><li><CheckCircle2/> RIBA Chartered Practice</li><li><CheckCircle2/> Residential specialist</li><li><CheckCircle2/> Midlands and Teesside</li></ul></div></div></section>
  <section className="section" id="process"><div className="shell twocol"><div><div className="eyebrow">Our process</div><h2>Four clear stages from first call to technical drawings.</h2></div><ol className="timeline">{[["01","Initial assessment",MessageSquare],["02","Measured survey",Ruler],["03","Design and planning",PenTool],["04","Technical drawings",Building2]].map(([n,t,I]:any)=><li key={n}><span>{n}</span><div><h3><I/>{t}</h3><p>Clear scope, agreed fee and a defined next step.</p></div></li>)}</ol></div></section>
  <section className="section sand" id="projects"><div className="shell"><div className="eyebrow">Selected projects</div><h2>Residential work across the Midlands and Teesside.</h2><div className="projects">{["1600585154340-be6161a56a0c","1600607687939-ce8a6c25118c","1600566753190-17f0baa2a6c3"].map((id,i)=><article key={id}><Image src={`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=85`} alt="Residential architecture project" width={1200} height={900}/><h3>{["House extension","Contemporary new home","Loft conversion"][i]}</h3></article>)}</div></div></section>
  <section className="section" id="services"><div className="shell"><div className="eyebrow">Services</div><h2>Three clear ways to work with us.</h2><div className="packages">{["Planning Essentials","Design & Approval","Complete Technical Package"].map((x,i)=><article className={i===1?"featured":""} key={x}><small>Stage {i+1}</small><h3>{x}</h3><ul><li><CheckCircle2/>Measured survey</li><li><CheckCircle2/>Design and planning</li><li><CheckCircle2/>Clear fixed-fee scope</li></ul><Link href="/estimate" className={i===1?"btn primary":"btn secondary"}>Get an indicative fee</Link></article>)}</div></div></section>
  <section className="section dark"><div className="shell cta"><div className="eyebrow">Ready when you are</div><h2>Let’s turn your project into a plan.</h2><Link href="/estimate" className="btn primary">Get my project estimate</Link></div></section>
 </>
}
